ARG DOCKER_IMAGE=ubuntu:focal
FROM $DOCKER_IMAGE

#Configure Ubuntu
RUN apt-get update && apt-get -y upgrade && apt-get install -yq locales tzdata software-properties-common apt-utils curl wget

#change to ru_RU.UTF-8 etc
RUN locale-gen "en_US.UTF-8"
RUN echo "LANG=en_US.UTF-8" >> /etc/default/locale
ENV LANG=en_US.UTF-8

#Change to "Europe/Moscow" etc
RUN echo "UTC" > /etc/timezone
RUN rm -f /etc/localtime
RUN dpkg-reconfigure -f noninteractive tzdata

# Install Java
RUN apt-get install -yq openjdk-11-jre-headless
# Install R
RUN apt-get install -yq r-base
